object Versions {
    const val daggerVersion = "2.48.1"
    const val hiltVersion = "1.2.0-alpha01"
    const val okhttpVersion = "4.11.0"
    const val coroutinesVersion = "1.7.1"
    const val retrofitVersion = "2.9.0"
    const val appCompatVersion = "1.6.1"
    const val kotlinVersion = "1.12.0"
    const val junitVersion = "4.13.2"
    const val testJunitVersion = "1.1.5"
    const val espressoVersion = "3.5.1"
    const val lifecycleVersion = "2.7.0"
    const val swipeRefreshVersion = "1.1.0"
    const val activityVersion = "1.8.2"
    const val materialVersion = "1.11.0"
    const val glideVersion = "4.14.2"
    const val roomVersion = "2.6.1"
    const val chuckerVersion = "4.0.0"
    const val multidexVersion = "2.0.1"
    const val shimmerVersion = "0.5.0"
    const val applicationVersion = "8.1.3"
    const val kspVersion = "1.9.20-1.0.14"
    const val jetbrainsKotlinVersion = "1.9.20"
    const val navigationVersion = "2.8.1"
    const val leakCanaryVersion = "3.0-alpha-1"
}