[versions]
accompanistPlaceholderMaterial = "0.33.2-alpha"
activityVersion = "1.9.2"
coilCompose = "2.5.0"
kotlin = "1.9.22"
kotlin-core = "1.12.0"
compose-ui = "1.7.8"
compose-material = "1.7.8"
compose-activity = "1.8.2"
compose-lifecycle = "2.7.0"
agp = "8.2.2"
appcompat = "1.7.0"
activity = "1.9.0"
material = "1.12.0"
junit = "4.13.2"
material3 = "1.3.1"
test-junit = "1.2.1"
espresso = "3.6.1"
dagger = "2.48.1"
hilt-compiler = "1.2.0"
okhttp = "4.12.0"
coroutines = "1.7.3"
retrofit = "2.9.0"
chucker = "4.0.0"
room = "2.6.1"
lifecycle = "2.8.7"
swipeRefresh = "1.1.0"
shimmer = "0.5.0"
glide = "4.16.0"
multidex = "2.0.1"
navigation = "2.8.9"
leakCanary = "2.12"
timber = "5.0.1"
jetbrainsKotlinJvm = "1.9.22"
ksp = "1.9.22-1.0.17"

[libraries]
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanistPlaceholderMaterial" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activityVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
dagger = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
swipe-refresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefresh" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
leak-canary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-core = { module = "androidx.core:core-ktx", version.ref = "kotlin-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }